### ISSUE TITLE
question: callback naming convention

### ISSUE THREAD

**Issue by boneskull** [vstirbu/fsm-as-promised#11]
All callbacks begin with `on` and must be lowercase, correct?  

Is there a reason they must be named this way?  Can the `on` prefix be entirely eliminated?

**Comment by vstirbu** [comment]
Only the `on{leave|enter|entered}` part has to be lowercase.

The reason is like this is because my initial state machines were implemented using [javascript-state-machine](https://github.com/jakesgordon/javascript-state-machine), therefore the convention for the callbacks was inherited from there.

Looks like we might get rid of the `on` prefix. I was planning some other changes that are backward incompatible, so it might be a good idea to gather them into a new issue so that we can bundle those features into 1.0.0 version.

**Comment by boneskull** [comment]
:+1: for ditching `on`.  If we can get rid of `on`, it appears we can also support camelCase, right?  `enterSomething`, `leaveSomething`, etc.  Could still just use lowercase for the internal representation...

**Comment by vstirbu** [comment]
Getting rid of `on` is straightforward but breaking change, as current fsm implementations use on for callbacks.

Did not get the comment about "internal representations"...

**Comment by vstirbu** [comment]
The new implementation allows to define a callback prefix as part of the static property. By default tits value would be `on` for backwards compatibility but it can be changed to `''`. 

Would that be enough for you?

**Comment by vstirbu** [comment]
Check this [branch](https://github.com/vstirbu/fsm-as-promised/tree/feature/callback-prefix) for an implementation proposal.

**Comment by vstirbu** [comment]
solved by 3e45f33c370e05a6adce0286330b783410838113
