### ISSUE TITLE
passing options between callbacks & error handling

### ISSUE THREAD

**Issue by boneskull** [vstirbu/fsm-as-promised#8]
Please see [this REPL](https://tonicdev.com/boneskull/fsm-as-promised-callback-error-handling) for an example.

Everything is fine & dandy until a callback throws an exception, which interrupts the promise chain.

Because there's nowhere to recover, the value of `foo` is lost, and depending on where the exception occurred, the FSM may not even enter the `started` state.

Using the new `EventEmitter` functionality would mitigate some of this, as a failing event handler shouldn't interrupt the promise chain (right?).  However, using the `EventEmitter` method, the user cannot pass data between the callbacks.

Potential solutions:

- A new callback, `onerror()`, which would give the user a chance to recover if a callback is rejected.  
- `onerror()` may be insufficient, since it may be difficult to tell which callback failed--and even if you could, you'd end up with conditionals or a `switch` statement in your error handling callback.  So, perhaps *every* potential callback needs an error handling callback.  `onleavestoppederror()`, `onleaveerror()`, `onstarterror()`, etc.
- Any new callbacks should be called with `options` still, or any extra data is lost; perhaps the error or rejected value could live in `options.err`.
- Instead, recover from all callbacks and pass any rejected values into `options.err`.
- Ignore this altogether and expect the user to recover from any failure in a callback.  This should probably be stated explicitly in the documentation, however.

([This other REPL](https://tonicdev.com/boneskull/fsm-as-promised-passing-data-between-event-handlers) may be a good example of how to pass data between event handlers--might want to put it in the docs?)

**Comment by vstirbu** [comment]
I tend to go for the last alternative:

> Ignore this altogether and expect the user to recover from any failure in a callback. This should probably be stated explicitly in the documentation, however.

As you mention there are six possible callbacks provided by the users that can be invoked during one transition. I think that this level of granularity gives already enough power to the developers to accommodate a wide range of application scenarios. However, due to this flexibility it is hard to come with a single mechanism that would enable recovery from any kind of error that may happen while triggering the transitions.

So, I'm aware that the current documentation on error handling is quite sketchy. One area that can improve the situation is to better describe the lifecycle of a transition and what are the implications in terms of error recovery. For example, the leave state and more importantly the enter state needs to be properly acknowledged by app developers as these are points of no return... Another one is that dev should handle expected sources of errors already in the callbacks and not let them roll to the trailing `catch`, where it is much more difficult to recover/rollback. 

In the end, an application developer has intimate knowledge about the particularities of the target environment and they can do a much better job at recovering than what the library can provide.

**Comment by boneskull** [comment]
fair 'nuff

**Comment by vstirbu** [comment]
@boneskull would it make sense to capture this result passing between callbacks in a more formal way? I would like to have something like:

```javascript
var fsm = StateMachine({
  initial: 'stopped',
  events: [{ name: 'start', from: 'stopped', to: 'started' }],
  callbacks: {
    onleavestopped: function (opts) {
      return {
        key: 'value'
      };
    },
    onstart: function (opts) {
      // opts.last.key === 'value'
      return {
        something: 'else'
      };
    }
  }
});

fsm.start().then(function (opts) {
  // opts.last.something === 'else'
});
```

Do you see any problems with this approach?
